import ChatConnect from '@/components/chatConnect'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { DM_Sans, Geist, Geist_Mono, JetBrains_Mono } from 'next/font/google'

import ThemeProvider from './context/themeProvider'
import ThemeWrapper from './context/ThemeWrapper'
import './globals.css'

const jetbrainsMono = JetBrains_Mono({
	subsets: ['latin'],
	variable: '--font-mono'
})

const dM_Sans = DM_Sans({ subsets: ['latin'], variable: '--font-dm-sans' })

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'CarHub',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='en'
			className={cn(
				'h-full',
				'antialiased',
				geistSans.variable,
				geistMono.variable,
				'font-mono',
				jetbrainsMono.variable
			)}
		>
			<body className='min-h-full flex flex-col'>
				<ThemeProvider>
					<ThemeWrapper>
						
						<ChatConnect />
						<main>{children}</main>
					</ThemeWrapper>
				</ThemeProvider>
			</body>
		</html>
	)
}
