import Footer from '@/components/footer'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'CarHub',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<>
			<main>{children}</main>
			<Footer />
		</>
	)
}
